/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Factory health and readiness
         * @description Factory health and readiness
         */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The factory line, policies and product lines
         * @description The factory line, policies and product lines
         */
        get: operations["get_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders, newest first
         * @description List orders, newest first
         */
        get: operations["list_orders"];
        put?: never;
        /**
         * Submit requirements; starts the first run
         * @description Submit requirements; starts the first run
         */
        post: operations["create_order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Order with its runs and feedback
         * @description Order with its runs and feedback
         */
        get: operations["get_order"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post-deploy feedback; starts the next iteration
         * @description Post-deploy feedback; starts the next iteration
         */
        post: operations["submit_feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run with station states
         * @description Run with station states
         */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Append-only event/decision log for a run
         * @description Append-only event/decision log for a run
         */
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer intake's blocking questions
         * @description Answer intake's blocking questions
         */
        post: operations["answer_questions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a held, interrupted or paused run
         * @description Resume a held, interrupted or paused run
         */
        post: operations["resume_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a run
         * @description Cancel a run
         */
        post: operations["cancel_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a decision or assumption in the run's append-only log
         * @description Record a decision or assumption in the run's append-only log
         */
        post: operations["log_decision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The active line: stations and agent specs
         * @description The active line: stations and agent specs
         */
        get: operations["get_line"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A specific (immutable) line version
         * @description A specific (immutable) line version
         */
        get: operations["get_line_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All line versions, newest first
         * @description All line versions, newest first
         */
        get: operations["list_line_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/versions/{version}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make a version the active line for new runs (runs in flight keep their version)
         * @description Make a version the active line for new runs (runs in flight keep their version)
         */
        post: operations["activate_line_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Choices for the editor: tool presets, model tiers, installed skills
         * @description Choices for the editor: tool presets, model tiers, installed skills
         */
        get: operations["get_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The editable draft of the line (created from the active version on first edit)
         * @description The editable draft of the line (created from the active version on first edit)
         */
        get: operations["get_draft"];
        put?: never;
        post?: never;
        /**
         * Throw the draft away
         * @description Throw the draft away
         */
        delete: operations["discard_draft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/draft/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create or update an agent in the draft
         * @description Create or update an agent in the draft
         */
        put: operations["put_draft_agent"];
        post?: never;
        /**
         * Delete an agent that no station uses
         * @description Delete an agent that no station uses
         */
        delete: operations["delete_draft_agent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/draft/agents/{agent_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy an agent under a new id
         * @description Copy an agent under a new id
         */
        post: operations["duplicate_draft_agent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/draft/stations/{station_id}/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Choose which agent runs an agent station
         * @description Choose which agent runs an agent station
         */
        put: operations["set_station_agent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/draft/docs/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create or update a reference document
         * @description Create or update a reference document
         */
        put: operations["put_draft_doc"];
        post?: never;
        /**
         * Delete a reference document no agent uses
         * @description Delete a reference document no agent uses
         */
        delete: operations["delete_draft_doc"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/line/draft/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate the draft and publish it as the next active line version
         * @description Validate the draft and publish it as the next active line version
         */
        post: operations["publish_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-sent events: live run events and status */
        get: operations["stream_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentSpec */
        AgentSpec: {
            /** Id */
            id: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Model
             * @default default
             */
            model: string;
            /**
             * Tools
             * @default observer
             * @enum {string}
             */
            tools: "observer" | "reviewer" | "author" | "operator" | "builder";
            /** Extra Tools */
            extra_tools?: string[];
            /** Disallowed Tools */
            disallowed_tools?: string[];
            /** Skills */
            skills?: string[];
            /**
             * Max Turns
             * @default 50
             */
            max_turns: number;
            /** Produces */
            produces?: string[];
            /** Context Docs */
            context_docs?: string[];
            /**
             * Previous Iterations
             * @default 0
             */
            previous_iterations: number;
            /**
             * Learnings
             * @default
             */
            learnings: string;
            /**
             * Prompt
             * @default
             */
            prompt: string;
        };
        /** AgentView */
        AgentView: {
            spec: components["schemas"]["AgentSpec"];
            /** Model Resolved */
            model_resolved: string;
            /** Effective Tools */
            effective_tools: string[];
            /** Observe Only */
            observe_only: boolean;
            /** Used By */
            used_by: string[];
        };
        /** AnswersInput */
        AnswersInput: {
            /** Answers */
            answers: string[];
        };
        /** CatalogView */
        CatalogView: {
            /** Presets */
            presets: {
                [key: string]: string[];
            };
            /** Observe Only Presets */
            observe_only_presets: string[];
            /** Extra Tools */
            extra_tools: string[];
            /** Model Tiers */
            model_tiers: {
                [key: string]: string;
            };
            /** Skills */
            skills: components["schemas"]["SkillInfo"][];
            /** Max Previous Iterations */
            max_previous_iterations: number;
            /** Max Doc Chars */
            max_doc_chars: number;
            /** Max Learnings Chars */
            max_learnings_chars: number;
        };
        /** ConfigView */
        ConfigView: {
            /** Name */
            name: string;
            /** Mode */
            mode: string;
            /** Line Version */
            line_version: number;
            /** Product Lines */
            product_lines: {
                [key: string]: string;
            };
            /** Stations */
            stations: components["schemas"]["StationView"][];
            /** Policies */
            policies: {
                [key: string]: string;
            };
            /** Gates */
            gates: string[];
        };
        /** CreateOrderInput */
        CreateOrderInput: {
            /** Title */
            title: string;
            /** Requirements */
            requirements: string;
            /**
             * Product Line
             * @default fastapi-service
             */
            product_line: string;
        };
        /** DecisionInput */
        DecisionInput: {
            /** Run Id */
            run_id: string;
            /** Station */
            station: string;
            /** Decision */
            decision: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** DraftView */
        DraftView: {
            /** Base Version */
            base_version: number;
            /** Active Version */
            active_version: number;
            /** Stale */
            stale: boolean;
            /** Dirty */
            dirty: boolean;
            /** Updated At */
            updated_at: string | null;
            /** Problems */
            problems: string[];
            /** Stations */
            stations: components["schemas"]["StationView"][];
            /** Agents */
            agents: components["schemas"]["AgentView"][];
            /** Docs */
            docs: components["schemas"]["RefDoc"][];
        };
        /** DuplicateAgentInput */
        DuplicateAgentInput: {
            /** New Id */
            new_id: string;
        };
        /** Event */
        Event: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Station */
            station?: string | null;
            kind: components["schemas"]["EventKind"];
            /** Message */
            message: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "station_started" | "station_finished" | "decision" | "log" | "agent" | "command" | "status" | "feedback";
        /** Feedback */
        Feedback: {
            /** Id */
            id: number;
            /** Order Id */
            order_id: string;
            /** Run Id */
            run_id: string | null;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FeedbackInput */
        FeedbackInput: {
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthView */
        HealthView: {
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Model Auth */
            model_auth: boolean;
            /** Github */
            github: boolean;
            /** Active Runs */
            active_runs: number;
        };
        /** LineVersionInfo */
        LineVersionInfo: {
            /** Line Id */
            line_id: string;
            /** Version */
            version: number;
            /** Note */
            note: string;
            /** Created At */
            created_at: string;
            /**
             * Active
             * @default false
             */
            active: boolean;
            /**
             * Stations
             * @default 0
             */
            stations: number;
            /**
             * Agents
             * @default 0
             */
            agents: number;
        };
        /** LineView */
        LineView: {
            /** Line Id */
            line_id: string;
            /** Version */
            version: number;
            /** Active */
            active: boolean;
            /** Note */
            note: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Blueprint */
            blueprint: string | null;
            /** Blueprint Update Available */
            blueprint_update_available: boolean;
            /** Stations */
            stations: components["schemas"]["StationView"][];
            /** Agents */
            agents: components["schemas"]["AgentView"][];
            /** Docs */
            docs?: components["schemas"]["RefDoc"][];
        };
        /** Order */
        Order: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Requirements */
            requirements: string;
            /** Product Line */
            product_line: string;
            /** Product Slug */
            product_slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latest Run Id */
            latest_run_id?: string | null;
            latest_status?: components["schemas"]["RunStatus"] | null;
            /** Node Port */
            node_port?: number | null;
            /** Host Port */
            host_port?: number | null;
            /** App Url */
            app_url?: string | null;
            /** Repo Url */
            repo_url?: string | null;
        };
        /** OrderDetail */
        OrderDetail: {
            order: components["schemas"]["Order"];
            /** Runs */
            runs: components["schemas"]["Run"][];
            /** Feedback */
            feedback: components["schemas"]["Feedback"][];
        };
        /** PublishInput */
        PublishInput: {
            /** Note */
            note: string;
        };
        /**
         * RefDoc
         * @description Team knowledge (standards, conventions, architecture rules) attached to agents.
         */
        RefDoc: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** Run */
        Run: {
            /** Id */
            id: string;
            /** Order Id */
            order_id: string;
            /** Iteration */
            iteration: number;
            status: components["schemas"]["RunStatus"];
            /** Current Station */
            current_station?: string | null;
            /**
             * Line Version
             * @default 1
             */
            line_version: number;
            /** Attempts */
            attempts?: {
                [key: string]: number;
            };
            /**
             * Loops
             * @default 0
             */
            loops: number;
            /** Change Request */
            change_request?: string | null;
            /** Last Failure */
            last_failure?: string | null;
            /** Questions */
            questions?: string[];
            /** Answers */
            answers?: string[];
            /** Resume At */
            resume_at?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RunDetail */
        RunDetail: {
            run: components["schemas"]["Run"];
            order: components["schemas"]["Order"];
            /** Stations */
            stations: components["schemas"]["StationView"][];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "needs_input" | "paused_limits" | "held" | "interrupted" | "awaiting_feedback" | "cancelled" | "failed";
        /** SkillInfo */
        SkillInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Vendored */
            vendored: boolean;
        };
        /** StationAgentInput */
        StationAgentInput: {
            /** Agent */
            agent: string;
        };
        /** StationView */
        StationView: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Role */
            role: string | null;
            /** Handler */
            handler: string;
            /** Repair */
            repair: boolean;
            /** State */
            state: string;
            /** Attempts */
            attempts: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    list_orders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
        };
    };
    create_order: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_questions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswersInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_decision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_line: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineView"];
                };
            };
        };
    };
    get_line_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_line_versions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineVersionInfo"][];
                };
            };
        };
    };
    activate_line_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineVersionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogView"];
                };
            };
        };
    };
    get_draft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
        };
    };
    discard_draft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
        };
    };
    put_draft_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_draft_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_draft_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateAgentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_station_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StationAgentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_draft_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefDoc"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_draft_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_draft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineVersionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
