/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Factory health and readiness
         * @description Factory health and readiness
         */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Factory settings: product lines, their workflow versions, policies, gates
         * @description Factory settings: product lines, their workflow versions, policies, gates
         */
        get: operations["get_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List orders, newest first
         * @description List orders, newest first
         */
        get: operations["list_orders"];
        put?: never;
        /**
         * Submit requirements; starts the first run
         * @description Submit requirements; starts the first run
         */
        post: operations["create_order"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Order with its runs and feedback
         * @description Order with its runs and feedback
         */
        get: operations["get_order"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post-deploy feedback; starts the next iteration
         * @description Post-deploy feedback; starts the next iteration
         */
        post: operations["submit_feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run with station states
         * @description Run with station states
         */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Append-only event/decision log for a run
         * @description Append-only event/decision log for a run
         */
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer intake's blocking questions
         * @description Answer intake's blocking questions
         */
        post: operations["answer_questions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume a held, interrupted or paused run
         * @description Resume a held, interrupted or paused run
         */
        post: operations["resume_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a run
         * @description Cancel a run
         */
        post: operations["cancel_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a decision or assumption in the run's append-only log
         * @description Record a decision or assumption in the run's append-only log
         */
        post: operations["log_decision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One workflow per product line
         * @description One workflow per product line
         */
        get: operations["list_workflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The active version of a workflow
         * @description The active version of a workflow
         */
        get: operations["get_workflow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A specific (immutable) workflow version
         * @description A specific (immutable) workflow version
         */
        get: operations["get_workflow_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All versions of a workflow, newest first
         * @description All versions of a workflow, newest first
         */
        get: operations["list_workflow_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/versions/{version}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make a version active for new runs (runs in flight keep theirs)
         * @description Make a version active for new runs (runs in flight keep theirs)
         */
        post: operations["activate_workflow_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Built-in workflow templates
         * @description Built-in workflow templates
         */
        get: operations["list_workflow_templates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft/from-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start the draft from a built-in template (publish to apply)
         * @description Start the draft from a built-in template (publish to apply)
         */
        post: operations["draft_from_template"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft/from-github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start the draft from a workflow template in a GitHub repo, pinned to a commit
         * @description Start the draft from a workflow template in a GitHub repo, pinned to a commit
         */
        post: operations["draft_from_github"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Choices for the editor: tool presets, model tiers, installed skills
         * @description Choices for the editor: tool presets, model tiers, installed skills
         */
        get: operations["get_catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The editable draft of a workflow (created from the active version on first edit)
         * @description The editable draft of a workflow (created from the active version on first edit)
         */
        get: operations["get_draft"];
        put?: never;
        post?: never;
        /**
         * Throw the draft away
         * @description Throw the draft away
         */
        delete: operations["discard_draft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create or update an agent in the draft
         * @description Create or update an agent in the draft
         */
        put: operations["put_draft_agent"];
        post?: never;
        /**
         * Delete an agent that no station uses
         * @description Delete an agent that no station uses
         */
        delete: operations["delete_draft_agent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft/agents/{agent_id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy an agent under a new id
         * @description Copy an agent under a new id
         */
        post: operations["duplicate_draft_agent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft/stations/{station_id}/agent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Choose which agent runs an agent station
         * @description Choose which agent runs an agent station
         */
        put: operations["set_station_agent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a station to the draft's lane (agent station or deterministic check)
         * @description Add a station to the draft's lane (agent station or deterministic check)
         */
        post: operations["add_draft_station"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft/stations/{station_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a station; routes pointing at it are cleared
         * @description Remove a station; routes pointing at it are cleared
         */
        delete: operations["delete_draft_station"];
        options?: never;
        head?: never;
        /**
         * Change a station's routes, repair flag, handler or agent (only the sent fields)
         * @description Change a station's routes, repair flag, handler or agent (only the sent fields)
         */
        patch: operations["update_draft_station"];
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft/stations/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the lane order (every station id exactly once)
         * @description Set the lane order (every station id exactly once)
         */
        put: operations["reorder_draft_stations"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft/docs/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create or update a reference document
         * @description Create or update a reference document
         */
        put: operations["put_draft_doc"];
        post?: never;
        /**
         * Delete a reference document no agent uses
         * @description Delete a reference document no agent uses
         */
        delete: operations["delete_draft_doc"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/draft/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate the draft and publish it as the next active version
         * @description Validate the draft and publish it as the next active version
         */
        post: operations["publish_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Skills agents can use: built-in and imported from GitHub
         * @description Skills agents can use: built-in and imported from GitHub
         */
        get: operations["list_skills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch a skill folder from GitHub for review: files, scripts, diff to the installed commit
         * @description Fetch a skill folder from GitHub for review: files, scripts, diff to the installed commit
         */
        post: operations["preview_skill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Install (or update to) the reviewed commit of a GitHub skill
         * @description Install (or update to) the reviewed commit of a GitHub skill
         */
        post: operations["install_skill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An imported skill: files, installed commits and users
         * @description An imported skill: files, installed commits and users
         */
        get: operations["get_skill"];
        put?: never;
        post?: never;
        /**
         * Remove an imported skill from the picker (blocked while a workflow uses it)
         * @description Remove an imported skill from the picker (blocked while a workflow uses it)
         */
        delete: operations["remove_skill"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/check-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch the latest commit of the skill's ref and diff it against the installed one
         * @description Fetch the latest commit of the skill's ref and diff it against the installed one
         */
        post: operations["check_skill_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-sent events: live run events and status */
        get: operations["stream_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddStationInput */
        AddStationInput: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "agent" | "check";
            /** Agent */
            agent?: string | null;
            /** Handler */
            handler?: string | null;
            /** On Fail */
            on_fail?: string | null;
            /** Next */
            next?: string | null;
            /**
             * Only On Fail
             * @default false
             */
            only_on_fail: boolean;
            /** Position */
            position?: number | null;
        };
        /** AgentSpec */
        AgentSpec: {
            /** Id */
            id: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Model
             * @default default
             */
            model: string;
            /**
             * Tools
             * @default observer
             * @enum {string}
             */
            tools: "observer" | "reviewer" | "author" | "operator" | "builder";
            /** Extra Tools */
            extra_tools?: string[];
            /** Disallowed Tools */
            disallowed_tools?: string[];
            /** Skills */
            skills?: string[];
            /**
             * Max Turns
             * @default 50
             */
            max_turns: number;
            /** Produces */
            produces?: string[];
            /** Context Docs */
            context_docs?: string[];
            /**
             * Previous Iterations
             * @default 0
             */
            previous_iterations: number;
            /**
             * Learnings
             * @default
             */
            learnings: string;
            /**
             * Prompt
             * @default
             */
            prompt: string;
        };
        /** AgentView */
        AgentView: {
            spec: components["schemas"]["AgentSpec"];
            /** Model Resolved */
            model_resolved: string;
            /** Effective Tools */
            effective_tools: string[];
            /** Observe Only */
            observe_only: boolean;
            /** Used By */
            used_by: string[];
        };
        /** AnswersInput */
        AnswersInput: {
            /** Answers */
            answers: string[];
        };
        /** CatalogView */
        CatalogView: {
            /** Presets */
            presets: {
                [key: string]: string[];
            };
            /** Observe Only Presets */
            observe_only_presets: string[];
            /** Extra Tools */
            extra_tools: string[];
            /** Model Tiers */
            model_tiers: {
                [key: string]: string;
            };
            /** Skills */
            skills: components["schemas"]["SkillInfo"][];
            /** Handlers */
            handlers: {
                [key: string]: string[];
            };
            /** Requirements */
            requirements: {
                [key: string]: {
                    [key: string]: boolean;
                };
            };
            /** Max Previous Iterations */
            max_previous_iterations: number;
            /** Max Doc Chars */
            max_doc_chars: number;
            /** Max Learnings Chars */
            max_learnings_chars: number;
        };
        /** ConfigView */
        ConfigView: {
            /** Name */
            name: string;
            /** Mode */
            mode: string;
            /** Workflows */
            workflows: {
                [key: string]: number;
            };
            /** Product Lines */
            product_lines: {
                [key: string]: string;
            };
            /** Policies */
            policies: {
                [key: string]: string;
            };
            /** Gates */
            gates: string[];
        };
        /** CreateOrderInput */
        CreateOrderInput: {
            /** Title */
            title: string;
            /** Requirements */
            requirements: string;
            /**
             * Product Line
             * @default fastapi-service
             */
            product_line: string;
        };
        /** DecisionInput */
        DecisionInput: {
            /** Run Id */
            run_id: string;
            /** Station */
            station: string;
            /** Decision */
            decision: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** DraftView */
        DraftView: {
            /** Workflow Id */
            workflow_id: string;
            /** Base Version */
            base_version: number;
            /** Active Version */
            active_version: number;
            /** Stale */
            stale: boolean;
            /** Dirty */
            dirty: boolean;
            /** Updated At */
            updated_at: string | null;
            /** Template */
            template?: string | null;
            /** Problems */
            problems: string[];
            /** Warnings */
            warnings?: string[];
            /** Skill Updates */
            skill_updates?: {
                [key: string]: string;
            };
            /** Stations */
            stations: components["schemas"]["StationView"][];
            /** Agents */
            agents: components["schemas"]["AgentView"][];
            /** Docs */
            docs: components["schemas"]["RefDoc"][];
        };
        /** DuplicateAgentInput */
        DuplicateAgentInput: {
            /** New Id */
            new_id: string;
        };
        /** Event */
        Event: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Station */
            station?: string | null;
            kind: components["schemas"]["EventKind"];
            /** Message */
            message: string;
            /** Data */
            data?: {
                [key: string]: unknown;
            };
        };
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "station_started" | "station_finished" | "decision" | "log" | "agent" | "command" | "status" | "feedback";
        /** Feedback */
        Feedback: {
            /** Id */
            id: number;
            /** Order Id */
            order_id: string;
            /** Run Id */
            run_id: string | null;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** FeedbackInput */
        FeedbackInput: {
            /** Text */
            text: string;
        };
        /** FromGitHubInput */
        FromGitHubInput: {
            /**
             * Repo
             * @description owner/name or https://github.com/owner/name
             */
            repo: string;
            /**
             * Path
             * @description folder containing workflow.yaml
             * @default
             */
            path: string;
            /**
             * Ref
             * @description branch, tag or commit sha (pinned to a commit on import)
             * @default main
             */
            ref: string;
        };
        /** FromTemplateInput */
        FromTemplateInput: {
            /** Template */
            template: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthView */
        HealthView: {
            /** Status */
            status: string;
            /** Mode */
            mode: string;
            /** Model Auth */
            model_auth: boolean;
            /** Github */
            github: boolean;
            /** Active Runs */
            active_runs: number;
        };
        /** InstallSkillInput */
        InstallSkillInput: {
            /** Repo */
            repo: string;
            /**
             * Path
             * @default
             */
            path: string;
            /**
             * Ref
             * @default main
             */
            ref: string;
            /** Sha */
            sha: string;
            /**
             * Accept Scripts
             * @default false
             */
            accept_scripts: boolean;
        };
        /** Order */
        Order: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Requirements */
            requirements: string;
            /** Product Line */
            product_line: string;
            /** Product Slug */
            product_slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Latest Run Id */
            latest_run_id?: string | null;
            latest_status?: components["schemas"]["RunStatus"] | null;
            /** Node Port */
            node_port?: number | null;
            /** Host Port */
            host_port?: number | null;
            /** App Url */
            app_url?: string | null;
            /** Repo Url */
            repo_url?: string | null;
        };
        /** OrderDetail */
        OrderDetail: {
            order: components["schemas"]["Order"];
            /** Runs */
            runs: components["schemas"]["Run"][];
            /** Feedback */
            feedback: components["schemas"]["Feedback"][];
        };
        /** PublishInput */
        PublishInput: {
            /** Note */
            note: string;
        };
        /**
         * RefDoc
         * @description Team knowledge (standards, conventions, architecture rules) attached to agents.
         */
        RefDoc: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** ReorderStationsInput */
        ReorderStationsInput: {
            /** Order */
            order: string[];
        };
        /** Run */
        Run: {
            /** Id */
            id: string;
            /** Order Id */
            order_id: string;
            /** Iteration */
            iteration: number;
            status: components["schemas"]["RunStatus"];
            /** Current Station */
            current_station?: string | null;
            /** Workflow Id */
            workflow_id?: string | null;
            /**
             * Workflow Version
             * @default 1
             */
            workflow_version: number;
            /** Attempts */
            attempts?: {
                [key: string]: number;
            };
            /**
             * Loops
             * @default 0
             */
            loops: number;
            /** Change Request */
            change_request?: string | null;
            /** Last Failure */
            last_failure?: string | null;
            /** Questions */
            questions?: string[];
            /** Answers */
            answers?: string[];
            /** Resume At */
            resume_at?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RunDetail */
        RunDetail: {
            run: components["schemas"]["Run"];
            order: components["schemas"]["Order"];
            /** Stations */
            stations: components["schemas"]["StationView"][];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "needs_input" | "paused_limits" | "held" | "interrupted" | "awaiting_feedback" | "cancelled" | "failed";
        /** SkillDetail */
        SkillDetail: {
            skill: components["schemas"]["SkillInfo"];
            /** Files */
            files: {
                [key: string]: string;
            };
            /** Versions */
            versions: components["schemas"]["SkillVersionInfo"][];
            /** Used By */
            used_by: string[];
        };
        /** SkillFile */
        SkillFile: {
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Script */
            script: boolean;
            /** Content */
            content: string;
        };
        /** SkillInfo */
        SkillInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Vendored */
            vendored: boolean;
            /**
             * Source
             * @default builtin
             * @enum {string}
             */
            source: "builtin" | "github";
            /** Repo */
            repo?: string | null;
            /** Path */
            path?: string | null;
            /** Ref */
            ref?: string | null;
            /** Sha */
            sha?: string | null;
            /** Scripts */
            scripts?: string[];
            /** Installed At */
            installed_at?: string | null;
        };
        /** SkillPreview */
        SkillPreview: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Repo */
            repo: string;
            /** Path */
            path: string;
            /** Ref */
            ref: string;
            /** Sha */
            sha: string;
            /** Files */
            files: components["schemas"]["SkillFile"][];
            /** Scripts */
            scripts: string[];
            /** Problems */
            problems: string[];
            /** Installed Sha */
            installed_sha?: string | null;
            /** Diff */
            diff?: string | null;
            /**
             * Up To Date
             * @default false
             */
            up_to_date: boolean;
        };
        /** SkillSourceInput */
        SkillSourceInput: {
            /** Repo */
            repo: string;
            /**
             * Path
             * @default
             */
            path: string;
            /**
             * Ref
             * @default main
             */
            ref: string;
        };
        /** SkillVersionInfo */
        SkillVersionInfo: {
            /** Sha */
            sha: string;
            /** Ref */
            ref: string;
            /** Installed At */
            installed_at: string;
            /** Current */
            current: boolean;
        };
        /** StationAgentInput */
        StationAgentInput: {
            /** Agent */
            agent: string;
        };
        /** StationView */
        StationView: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Role */
            role: string | null;
            /** Handler */
            handler: string;
            /** On Fail */
            on_fail?: string | null;
            /** Next */
            next?: string | null;
            /** Repair */
            repair: boolean;
            /** State */
            state: string;
            /** Attempts */
            attempts: number;
        };
        /** TemplateInfo */
        TemplateInfo: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Stations */
            stations: string[];
            /** Agents */
            agents: string[];
            /** Docs */
            docs: string[];
        };
        /**
         * UpdateStationInput
         * @description Only the fields that are sent are changed; send null to clear a route.
         */
        UpdateStationInput: {
            /** On Fail */
            on_fail?: string | null;
            /** Next */
            next?: string | null;
            /** Only On Fail */
            only_on_fail?: boolean | null;
            /** Handler */
            handler?: string | null;
            /** Agent */
            agent?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowSummary */
        WorkflowSummary: {
            /** Workflow Id */
            workflow_id: string;
            /** Product Line */
            product_line: string;
            /** Active Version */
            active_version: number;
            /** Description */
            description: string;
            /** Template */
            template: string | null;
            /** Stations */
            stations: number;
            /** Agents */
            agents: number;
            /** Draft Dirty */
            draft_dirty: boolean;
        };
        /** WorkflowVersionInfo */
        WorkflowVersionInfo: {
            /** Workflow Id */
            workflow_id: string;
            /** Version */
            version: number;
            /** Note */
            note: string;
            /** Created At */
            created_at: string;
            /**
             * Active
             * @default false
             */
            active: boolean;
            /**
             * Stations
             * @default 0
             */
            stations: number;
            /**
             * Agents
             * @default 0
             */
            agents: number;
        };
        /** WorkflowView */
        WorkflowView: {
            /** Workflow Id */
            workflow_id: string;
            /** Version */
            version: number;
            /** Active */
            active: boolean;
            /** Note */
            note: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Template */
            template: string | null;
            /** Template Update Available */
            template_update_available: boolean;
            /** Stations */
            stations: components["schemas"]["StationView"][];
            /** Agents */
            agents: components["schemas"]["AgentView"][];
            /** Docs */
            docs?: components["schemas"]["RefDoc"][];
            /** Warnings */
            warnings?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    list_orders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
        };
    };
    create_order: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_questions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswersInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_decision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowSummary"][];
                };
            };
        };
    };
    get_workflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflow_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowVersionInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_workflow_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowVersionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflow_templates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateInfo"][];
                };
            };
        };
    };
    draft_from_template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FromTemplateInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_from_github: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FromGitHubInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogView"];
                };
            };
        };
    };
    get_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_draft_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_draft_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    duplicate_draft_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateAgentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_station_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StationAgentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_draft_station: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddStationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_draft_station: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                station_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_draft_station: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                station_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_draft_stations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderStationsInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_draft_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefDoc"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_draft_doc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_draft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowVersionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillInfo"][];
                };
            };
        };
    };
    preview_skill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillSourceInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_skill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallSkillInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_skill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_skill_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
