"""StateStore seam. v0 = SQLite; scaled = Postgres behind the same protocol."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from agent_factory.models import (
    Change,
    ChangeStatus,
    EvalRun,
    Event,
    EventKind,
    Feedback,
    LearningProposal,
    Product,
    Transition,
)
from agent_factory.skills import SkillRecord
from agent_factory.workflow import WorkflowDoc, WorkflowVersionInfo


class StateStore(Protocol):
    # products
    def create_product(self, product: Product) -> Product: ...
    def get_product(self, product_id: str) -> Product | None: ...
    def list_products(self) -> list[Product]: ...
    def save_product(self, product: Product) -> None: ...

    # runs
    def create_change(self, change: Change) -> Change: ...
    def get_change(self, change_id: str) -> Change | None: ...
    def save_change(self, change: Change) -> None: ...
    def list_changes(self, product_id: str) -> list[Change]: ...
    def changes_with_status(self, statuses: set[ChangeStatus]) -> list[Change]: ...
    def all_changes(self) -> list[Change]: ...

    # status changes with their time (recorded by save_run; ADR-0019)
    def transitions(self, change_ids: list[str] | None = None) -> dict[str, list[Transition]]: ...

    # append-only event / decision log
    def add_event(
        self,
        change_id: str,
        kind: EventKind,
        message: str,
        station: str | None = None,
        data: dict[str, Any] | None = None,
    ) -> Event: ...
    def list_events(self, change_id: str, after_id: int = 0) -> list[Event]: ...
    def last_event_data(self, change_id: str, key: str) -> tuple[datetime, Any] | None: ...
    def first_event_time(self, change_id: str, message_prefix: str) -> datetime | None: ...
    def events_with_key(self, change_ids: list[str], key: str) -> list[tuple[str, datetime, Any]]: ...

    # learning proposals (ADR-0021): suggested by the retro, decided by an admin
    def add_proposal(self, p: LearningProposal) -> LearningProposal: ...
    def save_proposal(self, p: LearningProposal) -> None: ...
    def get_proposal(self, proposal_id: str) -> LearningProposal | None: ...
    def list_proposals(self, workflow_id: str, status: str | None = None) -> list[LearningProposal]: ...

    # periods the factory host was suspended (hostclock.py)
    def add_host_pause(self, start: datetime, end: datetime) -> None: ...
    def host_pauses(self, since: datetime | None = None) -> list[tuple[datetime, datetime]]: ...

    # evaluations (ADR-0025): a workflow version on its fixed suite, against a baseline
    def save_eval(self, e: EvalRun) -> EvalRun: ...
    def get_eval(self, eval_id: str) -> EvalRun | None: ...
    def list_evals(self, workflow_id: str) -> list[EvalRun]: ...

    # feedback
    def add_feedback(self, product_id: str, change_id: str | None, text: str) -> Feedback: ...
    def list_feedback(self, product_id: str) -> list[Feedback]: ...

    # versioned workflows (immutable versions; one active per workflow)
    def create_workflow_version(self, workflow_id: str, doc: WorkflowDoc, note: str) -> int: ...
    def get_workflow_version(self, workflow_id: str, version: int) -> WorkflowDoc | None: ...
    def active_workflow_version(self, workflow_id: str) -> int | None: ...
    def set_active_workflow_version(self, workflow_id: str, version: int) -> None: ...
    def list_workflow_versions(self, workflow_id: str) -> list[WorkflowVersionInfo]: ...

    # one editable draft per workflow (never runs; publishing turns it into a version)
    def get_workflow_draft(self, workflow_id: str) -> tuple[int, WorkflowDoc, str] | None: ...
    def save_workflow_draft(self, workflow_id: str, base_version: int, doc: WorkflowDoc) -> str: ...
    def delete_workflow_draft(self, workflow_id: str) -> None: ...
    def rename_workflow(self, old_id: str, new_id: str) -> None: ...

    # imported skills: every installed commit is kept; one is current per name
    def save_skill_version(self, rec: SkillRecord) -> None: ...
    def get_skill_version(self, name: str, sha: str) -> SkillRecord | None: ...
    def skill_versions(self, name: str) -> list[SkillRecord]: ...
    def set_current_skill(self, name: str, sha: str | None) -> None: ...
    def current_skill(self, name: str) -> SkillRecord | None: ...
    def current_skills(self) -> list[SkillRecord]: ...
