"""StateStore seam. v0 = SQLite; scaled = Postgres behind the same protocol."""

from __future__ import annotations

from typing import Any, Protocol

from agent_factory.models import Event, EventKind, Feedback, Order, Run, RunStatus
from agent_factory.workflow import WorkflowDoc, WorkflowVersionInfo


class StateStore(Protocol):
    # orders
    def create_order(self, order: Order) -> Order: ...
    def get_order(self, order_id: str) -> Order | None: ...
    def list_orders(self) -> list[Order]: ...
    def save_order(self, order: Order) -> None: ...

    # runs
    def create_run(self, run: Run) -> Run: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def save_run(self, run: Run) -> None: ...
    def list_runs(self, order_id: str) -> list[Run]: ...
    def runs_with_status(self, statuses: set[RunStatus]) -> list[Run]: ...

    # append-only event / decision log
    def add_event(
        self,
        run_id: str,
        kind: EventKind,
        message: str,
        station: str | None = None,
        data: dict[str, Any] | None = None,
    ) -> Event: ...
    def list_events(self, run_id: str, after_id: int = 0) -> list[Event]: ...

    # feedback
    def add_feedback(self, order_id: str, run_id: str | None, text: str) -> Feedback: ...
    def list_feedback(self, order_id: str) -> list[Feedback]: ...

    # versioned workflows (immutable versions; one active per workflow)
    def create_workflow_version(self, workflow_id: str, doc: WorkflowDoc, note: str) -> int: ...
    def get_workflow_version(self, workflow_id: str, version: int) -> WorkflowDoc | None: ...
    def active_workflow_version(self, workflow_id: str) -> int | None: ...
    def set_active_workflow_version(self, workflow_id: str, version: int) -> None: ...
    def list_workflow_versions(self, workflow_id: str) -> list[WorkflowVersionInfo]: ...

    # one editable draft per workflow (never runs; publishing turns it into a version)
    def get_workflow_draft(self, workflow_id: str) -> tuple[int, WorkflowDoc, str] | None: ...
    def save_workflow_draft(self, workflow_id: str, base_version: int, doc: WorkflowDoc) -> str: ...
    def delete_workflow_draft(self, workflow_id: str) -> None: ...
    def rename_workflow(self, old_id: str, new_id: str) -> None: ...
